# Generated by Django 3.2.6 on 2021-08-06 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bmi',
            name='user',
        ),
    ]
